### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by brettz9**
- CI: Add `.travis.yml`
- Docs: Add build, npm, and vulnerability/code quality badges

A couple things:

1. With `engines` showing Node 6+, I added the current versions from 6-14 to enforce that we are actually passing what we claim to support.  However, I got an email saying Travis is failing, but as I am in China behind the GFW, and without a functional VPN, so the Google Analytics or something in use at Travis prevents me from loading the page in a reasonably timely manner to see why why it's failing. I would guess it is because the latest versions of ESLint, etc. require Node 10. We can either add conditional logic to downgrade to older versions, or take the simpler route (as most projects seem to be doing these days) and just bump `engines` to 10 (since 6 and 8 are both [end-of-lifed](https://blog.risingstack.com/update-nodejs-8-end-of-life-no-support/) by Node) and drop the 6 and 8 in Travis.
2. Re: badges, I figured that since adding the Travis badge, it wouldn't hurt to add the others. Let me know if you want any of those removed.

### CODE REVIEW

**Comment by brettz9** [comment]
Btw, I don't remember if you need to visit the Travis site to enable it--you probably do need to add it as an integration if you want it to show up on pull requests as I think is a good idea. I also recommend the lgtm integration (see the sites in the LGTM badges I added) as it catches some things ESLint does not.

**Comment by n3ps** [comment]
Enabled Travis now, should reflect once this is in. 

Thanks for lgtm badges. Haven't used this before but it looks really useful.

As for david-dm, my take on that is because in the world of npm packages update every minute. Newer is better, but not always. I just don't want the potential of a user getting turned off from an "old" package.

**Comment by n3ps** [comment]
Also I'm fine with not specifying node <10 because of the EOL

**Comment by brettz9** [comment]
I dropped the (david-dm) npm dev badges and the Travis EOL versions (6 and 8). And just to confirm--you want to keep indicating support in `package.json` `engines` as 6+?

**Pull request merged**
