### PR TITLE
Array properties

### PR DESCRIPTION
**Pull request by brettz9**
feat: document arrays (including items)

Also finds arrays within objects and vice versa

Had a hunch this might not be too hard, so went ahead and added this.

It didn't look good to add the property as a type for array items when the type was missing (it would lead to "0" as a type, for example), I made it instead default to "any" (though I can't Google here, I chose "any" over "*" since, IIRC, TypeScript only recognizes "any") which I think is more accurate for an empty schema--unless we might allow "JSON" as the type instead. I could make it configurable, but wanted to know your thoughts on the default. "JSON" might not be recognized as a type out of the box, but it is more accurate than "any" since "any" could include non-JSON types too and a JSON schema only allows JSON.

The change to "any"/"JSON" raises another question... Can I make that as the default for object properties without types too? I think that would be more accurate.

### CODE REVIEW

**Comment by n3ps** [comment]
Does JSDoc allow type to be blank in `@property`? I think that accurately reflects the scenario when the schema is untyped. `any` might be the second best alternative since that's in TS. Introducing a keyword `JSON` might be odd since that doesn't exist in the JS ecosystem yet.

**Comment by brettz9** [comment]
I don't see it made explicit that `@property`'s type can be blank. However:

1. `@param` clearly allows avoiding the type per https://jsdoc.app/tags-param.html#names-types-and-descriptions , and the two are quite similar.
2. Running `jsdoc` does let you build docs that avoid a type for `@property`, e.g., for:

```js
/**
 * @typedef {object}
 * @property name A person's name
 * @property [age] A person's age
 */
```

...I get:

image

While I see your argument about it possibly being typeless, maybe it can be made configurable. Looking at [JSON Schema](http://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.4.3.2), though in the context of speaking of boolean schemas, mentions that a boolean `true` schema equals the empty schema object and that this means it passes validation:

> true:
>     Always passes validation, as if the empty schema {} 

and while JSON Schema advises use of the boolean for "human readers", it nevertheless states that:

> ...the empty schema object is unambiguous

To me this suggests any type is explicitly being allowed when such a schema is used.

If you do want to make it configurable, I guess one might argue on whether to accept "any" by default since `*` is the only one mentioned in the jsdoc docs that I can see. See the "Allows any type" section at https://jsdoc.app/tags-param.html#multiple-types-and-repeatable-parameters.

While I can see if you wouldn't want it as the default since there is no accepted convention for it, ss far as use of "JSON", I just want to mention that it is at least permissible to use this if that wasn't clear. Types *can* accept arbitrary types in jsdoc, both because:

1. The doc builder won't complain even if a type can't be found to be defined elsewhere in the code (it just won't link to it.
2. The docs at https://jsdoc.app/tags-param.html#overview explicitly state:

> The parameter type can be a built-in JavaScript type, such as string or Object, or **a JSDoc namepath to another symbol in your code**

...so it would at least be valid (and linked in jsdoc-built docs) if one had something like this elsewhere in their code (as I would do):

```js
/**
 * @typedef {null|boolean|number|string|JSON[]|object<string,JSON>} JSON
 */
```

Another possibility is if one wanted to define `JSON` as [`@external`](https://jsdoc.app/tags-external.html)

```js
/**
 * @external JSON
 * @see https://www.json.org/json-en.html
 */
```

...requiring the type be output as "external:JSON" instead of "JSON", e.g.,:


```js
/**
 * @property {external:JSON} anArg
 */
```

Anyways, I see good reasons either way, so I'd like to make it at least configurable, if that's ok, though if it is, let me know which default (or if you want the absence of the option to omit the type, and then the user can configure it to "any", "*", "JSON", "external:JSON", etc. as they prefer).

**Comment by brettz9** [comment]
Also, if you could let me know whether you still want use of the title (auto-capitalized or not) as the type, and if so, how.

e.g., from the tests, this can get built when there is no `type`:

```js
 * @property {ANestedProp} [anObjectProp.aNestedProp]
```

**Comment by n3ps** [comment]
Thanks. I see your point about a JSON type and the concept of an external type. In the context of ambiguity, it's very hard to guess the user's intention though. Simply overlooked for example.

Working backwards and since JSDoc does mention `*` I think that's the closest to an untyped default we can get. 

For the untyped `aNestedProp` example it will become `@property {*} {anObjectProp.aNestedProp}` then.

**Comment by n3ps** [comment]
@brettz9 I'm planning to merge the refactor since this adds more code, but I checked and it's straightforward to make it compatible. In `processItems`, just follow the pattern of:
```
const result = []
result.push(writeProperty(...))
result.push(...processItems(...))
```

And it should be good.

**Comment by brettz9** [comment]
Amended.

I also cached `properties[props]` for performance and readability and removed the default array in the `format` signature since it was causing it to be shown as an uncovered "else" branch (i.e., it wasn't possible in our current code to use the default array).

**Comment by brettz9** [comment]
And just now amended further as I realized I hadn't fixed the default to `*`. I can make a separate PR if you like to apply it to objects as well, and add configuration therefor if that's ok.

**Comment by brettz9** [comment]
Btw, the reason I had the variable titled `name` instead of `typeDescription` as you changed it, is because [`typedef`](https://jsdoc.app/tags-typedef.html) doesn't allow a full description--only a name/namepath. I think reverting to `name` or changing to `namepath` is still the most suitable name here.

**Comment by n3ps** [comment]
Interesting, I didn't know that default values would do that to test coverage.

If you check again, the `typeDescription` was simply an exctraction of an inline nested "ternary-within-template literal" and was a bit hard to read. It can still be made more readable and if there's a better variable name go for it on the next change.

**Pull request merged**
